# Week 1

As proposed we'll cover time-series statistics and conduct...
Make sure to follow the content well at your own pace.

## Time-series statistics

### What's the frequency, Kenneth?

1. A time series is simply a sequence of data points indexed...
Unlike standard cross-sectional data, time-series observatio...

2. Characteristics of a time series:
   - **Trend:** The long-term drift or structural direction...
   - **Seasonality:** Predictable, periodic fluctuations th...
   - **Volatility Clustering:** The tendency for high-volat...
   - **Non-linearity:** Structural breaks and regime shifts...
